services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
            - ./.env:/app/.env
        ports:
            - '8001:8001'
        depends_on:
            minio:
                condition: service_healthy
        command: >
            sh -c "pnpm install && pnpm build && pnpm start"
        environment:
            - .env
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:8001/health']
            interval: 30s
            timeout: 10s
            retries: 5
