services:
    minio:
        image: minio/minio
        container_name: minio
        volumes:
            - minio_data:/data
        environment:
            - MINIO_ROOT_USER=minioadmin
            - MINIO_ROOT_PASSWORD=minioadmin
        command: server /data --console-address ":9001"
        ports:
            - '9000:9000'
            - '9001:9001'
        healthcheck:
            test:
                ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
            interval: 30s
            timeout: 10s
            retries: 3

    mc:
        image: minio/mc
        container_name: mc
        depends_on:
            minio:
                condition: service_healthy
        entrypoint: >
            /bin/sh -c "
              mc alias set local http://minio:9000 minioadmin minioadmin &&
              mc mb --ignore-existing local/uploads &&
              mc anonymous set download local/uploads &&
              echo '✅ Bucket uploads created and set public'
            "

    backend:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
            - ./.env:/app/.env
        ports:
            - '8001:8001'
        depends_on:
            minio:
                condition: service_healthy
        command: >
            sh -c "pnpm install && pnpm build && pnpm start"

volumes:
    minio_data:
